# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fetchgit, mtl }:

cabal.mkDerivation (self: {
  pname = "geniplate";
  version = "0.6.0.6";
  src = fetchgit {
    url = "git@github.com:augustss/geniplate.git";
    sha256 = "ca8783c0addfd63f9d2c7e9bb6757d96be4851c1f44e4e29c01700f113aa831c";
    rev = "3e7719df7b2ca637543ef26326e6659fcb44ed23";
  };
  buildDepends = [ mtl ];
  meta = {
    description = "Use Template Haskell to generate Uniplate-like functions";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
