# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, async, zlib }:

cabal.mkDerivation (self: {
  pname = "minisat";
  version = "0.1.1";
  sha256 = "1myy23mrhnm7wv6mzyym9jmw8pnlqkfam9dl082i8qll3mxrl83i";
  buildDepends = [ async ];
  extraLibraries = [ zlib ];
  meta = {
    description = "A Haskell bundle of the Minisat SAT solver";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
