# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, alex, binary, filepath, hashable, minisat, mtl
, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "jukebox";
  version = "0.1.2";
  sha256 = "01gdb7wi65idws4q2bbxzna07s3y0wd4p7npawm7rdiyfp3pg92k";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    binary filepath hashable minisat mtl unorderedContainers
  ];
  buildTools = [ alex ];
  meta = {
    description = "A first-order reasoning toolbox";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
