# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, constraints, dlist, fetchzip, jukebox, pqueue, QuickCheck
, random, spoon, termRewriting, transformers, uglymemo, z3
}:

cabal.mkDerivation (self: {
  pname = "quickspec";
  version = "0.9.6";
  src = fetchzip {
    url = "https://github.com/nick8325/quickspec/archive/v2.zip";
    sha256 = "1lh207hcm0r6ybab5025ylq0l6nlb3qrvfvyyrk1wn50cn9hril4";
  };
  buildDepends = [
    constraints dlist jukebox pqueue QuickCheck random spoon
    termRewriting transformers uglymemo z3
  ];
  meta = {
    homepage = "https://github.com/nick8325/quickspec";
    description = "Equational laws for free!";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
