# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, QuickCheck, random, spoon, transformers }:

cabal.mkDerivation (self: {
  pname = "quickspec";
  version = "0.9.6";
  sha256 = "0prwzxsrvfqryl75rmma229d4y7ra61vc3d72kyqi4l44ga2ay21";
  buildDepends = [ QuickCheck random spoon transformers ];
  meta = {
    homepage = "https://github.com/nick8325/quickspec";
    description = "Equational laws for free!";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
