# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ansiWlPprint, mtl, multiset, parsec, unionFindArray
}:

cabal.mkDerivation (self: {
  pname = "term-rewriting";
  version = "0.1.2.2";
  sha256 = "0j69a4vvsv5lbh8zx3908bpk76lmg871glm6hqv0nq4xzircp184";
  buildDepends = [ ansiWlPprint mtl multiset parsec unionFindArray ];
  doCheck = false;
  #testDepends = [ HUnit QuickCheck ];
  meta = {
    homepage = "http://cl-informatik.uibk.ac.at/software/haskell-rewriting/";
    description = "Term Rewriting Library";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
