# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ansiWlPprint, HUnit, mtl, multiset, parsec, QuickCheck
, unionFindArray
}:

cabal.mkDerivation (self: {
  pname = "term-rewriting";
  version = "0.1.2.1";
  sha256 = "06lz89dhaq6pqp1zjx8bmgpx06fq3xgnqy1llipik5c9zyr4zrfv";
  buildDepends = [ ansiWlPprint mtl multiset parsec unionFindArray ];
  testDepends = [ HUnit QuickCheck ];
  meta = {
    homepage = "http://cl-informatik.uibk.ac.at/software/haskell-rewriting/";
    description = "Term Rewriting Library";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
