# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, mtl }:

cabal.mkDerivation (self: {
  pname = "union-find-array";
  version = "0.1.0.2";
  sha256 = "1pxb1v2k04i8ds2n8zqra74gacry6dj5p87sxgkf4fazx4s316dk";
  buildDepends = [ mtl ];
  meta = {
    homepage = "https://github.com/haskell-rewriting/union-find-array";
    description = "union find data structure";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
