#!/usr/bin/env bash
set -ex
HOST=$(hostname)
NIXPKGS=$(nix-instantiate --eval nixpkgs.nix | tr -d '"')
REMOTE_IP=$(getent ahostsv4 "${S5_HOST:-s5.local}" | cut -d' ' -f1 | head -n1)
REMOTE="${S5_USER:-nixos}@${REMOTE_IP}"
sudo nixos-rebuild \
    --use-remote-sudo \
    --target-host "$REMOTE" \
    --build-host "${USER}@${HOST}" \
    switch \
    -I nixos-config="$PWD/configuration.nix" \
    -I nixpkgs="$NIXPKGS" \
    --option extra-substituters "ssh://${REMOTE}" \
    --option require-sigs false
